/*
 * mortality.js -- survival probabilities from the SSA period life table
 * (self.SWR_MORTALITY, generated by tools/fetch_mortality.py). Main-thread only
 * (the chart overlay); the engine's failure probabilities come from the summary.
 */
(function (root) {
  "use strict";
  const SWR = (root.SWR = root.SWR || {});

  // P(alive at year t), t = 0..years, starting at `age`. sex: "male"|"female"|"blended".
  function survivalCurve(age, sex, years) {
    const M = root.SWR_MORTALITY;
    if (!M) return null;
    const fa = M.firstAge, la = M.lastAge;
    const a0 = Math.max(fa, Math.min(la, Math.round(age) || fa));
    const lx = (arr, a) => (a > la ? 0 : arr[a - fa]);
    const out = new Array(years + 1);
    if (sex === "blended") {
      const bm = M.male.l[a0 - fa] || 1, bf = M.female.l[a0 - fa] || 1;
      for (let t = 0; t <= years; t++) {
        out[t] = ((bm > 0 ? lx(M.male.l, a0 + t) / bm : 0) +
                  (bf > 0 ? lx(M.female.l, a0 + t) / bf : 0)) / 2;
      }
    } else {
      const l = (sex === "female" ? M.female : M.male).l;
      const base = l[a0 - fa] || 1;
      for (let t = 0; t <= years; t++) out[t] = base > 0 ? lx(l, a0 + t) / base : 0;
    }
    return out;
  }

  // Remaining life expectancy (years) at `age`.
  function lifeExpectancy(age, sex) {
    const M = root.SWR_MORTALITY;
    if (!M) return null;
    const i = Math.max(M.firstAge, Math.min(M.lastAge, Math.round(age) || M.firstAge)) - M.firstAge;
    if (sex === "female") return M.female.e[i];
    if (sex === "male") return M.male.e[i];
    return (M.male.e[i] + M.female.e[i]) / 2;
  }

  SWR.mortality = { survivalCurve, lifeExpectancy };
})(typeof self !== "undefined" ? self : this);
