#!/usr/bin/env python3
"""
fetch_mortality.py -- compile the SSA Actuarial (period) Life Table into a
bundled data file the browser app loads. Pure Python standard library.

Source: U.S. Social Security Administration, Period Life Table (public domain).
  https://www.ssa.gov/oact/STATS/table4c6.html

This tool is deliberately NETWORK-FREE and NOT for cron automation: SSA's edge
hard-403s every non-browser client (verified against curl and urllib, with both
honest and browser User-Agents), so it reads a browser-saved copy from
tools/.cache/ssa_life_table.html instead. To refresh (~once a year, when SSA
publishes a new period life table): open the URL in a browser, Save Page As HTML
into tools/.cache/ssa_life_table.html, and re-run. The saved file is treated as
untrusted input: numbers are finiteness-checked, the one scraped string is
whitelisted, and the output is written atomically.

Output:
  ../js/mortality-data.js   self.SWR_MORTALITY = { male:{l,e}, female:{l,e}, ... }
    l(x) = survivors per 100,000 at exact age x; e(x) = life expectancy at age x.
"""
import json
import math
import os
import re
import sys
from datetime import date
from html.parser import HTMLParser

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, ".cache", "ssa_life_table.html")
SRC_URL = "https://www.ssa.gov/oact/STATS/table4c6.html"


class TableParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows, self.cur, self.cell = [], None, None

    def handle_starttag(self, tag, attrs):
        if tag == "tr":
            self.cur = []
        elif tag in ("td", "th"):
            self.cell = []

    def handle_endtag(self, tag):
        if tag in ("td", "th") and self.cell is not None:
            self.cur.append(re.sub(r"\s+", " ", "".join(self.cell)).strip())
            self.cell = None
        elif tag == "tr" and self.cur is not None:
            self.rows.append(self.cur)
            self.cur = None

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)


def num(s):
    s = s.replace(",", "").strip()
    return float(s)


def main():
    if not os.path.exists(CACHE):
        sys.exit("FATAL: missing " + os.path.relpath(CACHE, ROOT) +
                 "\n  SSA blocks scripted downloads. Open " + SRC_URL +
                 "\n  in a browser, save the page as HTML to that path, and re-run.")
    html = open(CACHE, encoding="utf-8", errors="replace").read()
    title = re.search(r"Period Life Table[^<]*\d{4}[^<]*", html)
    title = title.group(0).strip() if title else "SSA Period Life Table"
    # The ONLY scraped string that reaches the served JS. json.dumps escaping
    # already makes it inert; whitelist + cap anyway (defense in depth).
    title = re.sub(r"[^\w ,.()\-]", "", title)[:100]

    p = TableParser()
    p.feed(html)
    # Data rows: Age | M q(x) l(x) e(x) | F q(x) l(x) e(x)
    rows = [r for r in p.rows if r and re.match(r"^\d{1,3}$", r[0].strip()) and len(r) >= 7]
    ages = [int(r[0]) for r in rows]
    male_l = [num(r[2]) for r in rows]
    male_e = [num(r[3]) for r in rows]
    female_l = [num(r[5]) for r in rows]
    female_e = [num(r[6]) for r in rows]

    checks = [
        ("ages 0..119 contiguous", ages == list(range(0, 120))),
        # float() accepts "Infinity"/"NaN", which would emit as bare inf/nan --
        # INVALID JS that would break the served file. Refuse them loudly.
        ("all values finite", all(math.isfinite(v) for s in (male_l, male_e, female_l, female_e) for v in s)),
        ("male l(0)=100000", male_l[0] == 100000),
        ("female l(0)=100000", female_l[0] == 100000),
        ("male l non-increasing", all(male_l[i] >= male_l[i + 1] for i in range(len(male_l) - 1))),
        ("female l non-increasing", all(female_l[i] >= female_l[i + 1] for i in range(len(female_l) - 1))),
        ("male e(65) ~ 18", 16 < male_e[65] < 20),
        ("female e(65) ~ 21", 18 < female_e[65] < 23),
        ("women outlive men at 65", female_l[65] > male_l[65]),
    ]
    print("Sanity checks:")
    ok = True
    for name, passed in checks:
        print(f"  [{'PASS' if passed else 'FAIL'}] {name}")
        ok = ok and passed
    if not ok:
        sys.exit("FATAL: SSA table sanity checks failed.")

    def arr(a):
        return "[" + ",".join(f"{int(v)}" if float(v).is_integer() else f"{v:g}" for v in a) + "]"

    meta = {
        "source": title,
        "url": SRC_URL,
        "publisher": "U.S. Social Security Administration (public domain)",
        "note": "l(x) = survivors per 100,000 at exact age x; e(x) = life expectancy (years) at age x.",
        "generated": date.today().isoformat(),
        "firstAge": 0, "lastAge": 119,
    }
    js = ["// AUTO-GENERATED by tools/fetch_mortality.py. Do NOT edit by hand.",
          "// SSA period life table (public domain). l(x)=survivors/100k, e(x)=life expectancy.",
          "self.SWR_MORTALITY = {",
          '"meta":' + json.dumps(meta, indent=0).replace("\n", " ") + ",",
          '"firstAge":0,"lastAge":119,',
          '"male":{"l":' + arr(male_l) + ',"e":' + arr(male_e) + "},",
          '"female":{"l":' + arr(female_l) + ',"e":' + arr(female_e) + "}",
          "};", ""]
    out = os.path.join(ROOT, "js", "mortality-data.js")
    # Atomic replace: nothing reading concurrently (e.g. a docker build) can ever
    # observe a half-written, syntactically-broken file.
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("\n".join(js))
    os.replace(tmp, out)
    print("\nWrote", os.path.relpath(out, ROOT))
    print(f"  {title}")
    print(f"  life expectancy at 65: male {male_e[65]:.1f}y, female {female_e[65]:.1f}y")
    print(f"  survival to 90 from 65: male {male_l[90] / male_l[65] * 100:.0f}%, "
          f"female {female_l[90] / female_l[65] * 100:.0f}%")


if __name__ == "__main__":
    main()
